<div class="warranty-container">
    <div class="warranty-transfer-container" data-bind="scope: 'warranty-transfer'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/javascript">
        /**
         * @Hidro-Le
         * @TODO - Review
         * getInitData function này không tồn tại
         */
        window.InitData = <?= /* @noEscape */ $block->getInitData() ?>;
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>
