<?php
/** @var Variux\Warranty\Block\Suggestion\Engine $block */
$engineConfig = $block->getEngineSuggestConfig();
?>
<div class="suggestion-engine-container">
    <div class="suggestion-wrapper" data-bind="scope: 'suggestion-engine'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            },
                "Variux_Warranty/js/lib/suggestion/engine": {
                "engineConfig": <?= /* @escapeNotVerified */ \Zend_Json::encode($engineConfig) ?>
            }
        }
    </script>
</div>

